version: '3'

services:

  app:
    container_name: adocao-de-pets-back-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    restart: always
    depends_on:
      - postgres
    networks:
      - net
  

  postgres:
    container_name: postgres
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pet-adoption
    networks:
      - net

networks:
  net: